Repository Epistimio/orion, pull requests merged in 2019-10, with the labels that each got.

#288 Save parser state in DB
  src/orion/core/evc/conflicts.py
  src/orion/core/io/cmdline_parser.py
  src/orion/core/io/convert.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/orion_cmdline_parser.py
  src/orion/core/utils/tests.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  tests/conftest.py
  tests/functional/commands/conftest.py
  tests/functional/demo/test_demo.py
  tests/functional/gradient_descent_algo/setup.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/io/test_cmdline_parser.py
  tests/unittests/core/io/test_converters.py
  tests/unittests/core/io/test_orion_cmdline_parser.py
  tests/unittests/core/sample_config_template.txt
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_experiment.py
Labels: v0.1.7

#290 Fix deepcopy of Enumerate transform
  src/orion/core/worker/transformer.py
  tests/unittests/core/test_transformer.py
Labels: bug, v0.1.7

#284 Handle non-existing fields in EphemeralDB
  src/orion/core/io/database/ephemeraldb.py
  tests/unittests/core/test_ephemeraldb.py
Labels: bug, v0.1.7

#287 Add mention of windows in install doc
  docs/src/install/core.rst
Labels: documentation, v0.1.7

#285 Add functional tests for backward-compatibility
  .travis.yml
  src/orion/core/cli/test_db.py
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/utils/backward.py
  src/orion/core/utils/tests.py
  src/orion/core/worker/experiment.py
  tests/conftest.py
  tests/functional/backward_compatibility/black_box.py
  tests/functional/backward_compatibility/random.yaml
  tests/functional/backward_compatibility/test_versions.py
  tests/functional/commands/conftest.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_experiment.py
  tox.ini
Labels: v0.1.7

#291 Turn test-db into db test
  docs/src/code/core/cli.rst
  docs/src/code/core/cli/db.rst
  docs/src/code/core/cli/db/setup.rst
  docs/src/code/core/cli/db/test.rst
  docs/src/code/core/cli/test_db.rst
  docs/src/install/database.rst
  src/orion/core/cli/db/__init__.py
  src/orion/core/cli/db/setup.py
  src/orion/core/cli/db/test.py
  src/orion/core/cli/db_main.py
  src/orion/core/cli/setup.py
  src/orion/core/cli/test_db.py
  tests/functional/backward_compatibility/test_versions.py
  tests/functional/commands/test_setup_command.py
Labels: v0.1.7

#292 Update skopt doc and prepare v0.1.7
  ROADMAP.md
  docs/src/user/algorithms.rst
Labels: v0.1.7

#293 Add `orion db upgrade` command
  docs/src/install/database.rst
  src/orion/core/cli/db/upgrade.py
  src/orion/core/io/database/__init__.py
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/utils/backward.py
  src/orion/storage/base.py
  src/orion/storage/legacy.py
  tests/conftest.py
  tests/functional/backward_compatibility/test_versions.py
  tests/unittests/storage/test_legacy.py
  tests/unittests/storage/test_storage.py
Labels: v0.1.7

#295 Instantiate adapter even if empty
  src/orion/core/worker/experiment.py
  tests/unittests/core/worker/test_experiment.py
Labels: bug, v0.1.7

#296 Release v0.1.7rc2
  .travis.yml
  ROADMAP.md
  docs/src/code/core/cli.rst
  docs/src/code/core/cli/db.rst
  docs/src/code/core/cli/db/setup.rst
  docs/src/code/core/cli/db/test.rst
  docs/src/code/core/cli/test_db.rst
  docs/src/install/core.rst
  docs/src/install/database.rst
  docs/src/user/algorithms.rst
  src/orion/core/cli/db/__init__.py
  src/orion/core/cli/db/setup.py
  src/orion/core/cli/db/test.py
  src/orion/core/cli/db/upgrade.py
  src/orion/core/cli/db_main.py
  src/orion/core/cli/setup.py
  src/orion/core/cli/test_db.py
  src/orion/core/evc/conflicts.py
  src/orion/core/io/cmdline_parser.py
  src/orion/core/io/convert.py
  src/orion/core/io/database/__init__.py
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/orion_cmdline_parser.py
  src/orion/core/utils/backward.py
  src/orion/core/utils/tests.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/transformer.py
  src/orion/storage/base.py
  src/orion/storage/legacy.py
  tests/conftest.py
  tests/functional/backward_compatibility/black_box.py
  tests/functional/backward_compatibility/random.yaml
  tests/functional/backward_compatibility/test_versions.py
  tests/functional/commands/conftest.py
  tests/functional/commands/test_setup_command.py
  tests/functional/demo/test_demo.py
  tests/functional/gradient_descent_algo/setup.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/io/test_cmdline_parser.py
  tests/unittests/core/io/test_converters.py
  tests/unittests/core/io/test_orion_cmdline_parser.py
  tests/unittests/core/sample_config_template.txt
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/test_ephemeraldb.py
  tests/unittests/core/test_transformer.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/storage/test_legacy.py
  tests/unittests/storage/test_storage.py
  tox.ini
Labels: release, v0.1.7

#289 Track integration2
  conda/conda_build.sh
  docs/src/user/library/results.rst
  setup.py
  src/orion/core/utils/tests.py
  src/orion/core/worker/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/trial.py
  src/orion/storage/base.py
  src/orion/storage/track.py
  tests/requirements.txt
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/storage/test_legacy.py
  tests/unittests/storage/test_storage.py
Labels: v0.1.8

#302 remove ExperienceAdapter
  src/orion/storage/track.py
Labels: v0.1.8

#297 Refactor experiment builder
  docs/src/code/core/io.rst
  docs/src/code/core/io/evc_builder.rst
  src/orion/client/manual.py
  src/orion/core/__init__.py
  src/orion/core/cli/__init__.py
  src/orion/core/cli/base.py
  src/orion/core/cli/checks/presence.py
  src/orion/core/cli/db/test.py
  src/orion/core/cli/db/upgrade.py
  src/orion/core/cli/evc.py
  src/orion/core/cli/hunt.py
  src/orion/core/cli/info.py
  src/orion/core/cli/init_only.py
  src/orion/core/cli/insert.py
  src/orion/core/cli/list.py
  src/orion/core/cli/status.py
  src/orion/core/evc/conflicts.py
  src/orion/core/evc/experiment.py
  src/orion/core/io/config.py
  src/orion/core/io/evc_builder.py
  src/orion/core/io/experiment_branch_builder.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/resolve_config.py
  src/orion/core/utils/backward.py
  src/orion/core/utils/tests.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  src/orion/storage/legacy.py
  tests/conftest.py
  tests/functional/backward_compatibility/test_versions.py
  tests/functional/branching/test_branching.py
  tests/functional/commands/conftest.py
  tests/functional/commands/test_insert_command.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/cli/test_checks.py
  tests/unittests/core/cli/test_evc.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/conftest.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/evc/test_resolutions.py
  tests/unittests/core/io/interactive_commands/test_branching_prompt.py
  tests/unittests/core/io/test_config.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/test_producer.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/core/worker/test_trial_pacemaker.py
  tests/unittests/storage/test_storage.py
Labels: v0.1.8

#299 Add Space definition in DB
  src/orion/algo/space.py
  src/orion/core/cli/db/upgrade.py
  src/orion/core/evc/conflicts.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/utils/backward.py
  src/orion/core/worker/experiment.py
  tests/conftest.py
  tests/functional/commands/conftest.py
  tests/unittests/algo/test_space.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/io/test_space_builder.py
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/test_ephemeraldb.py
  tests/unittests/core/test_pickleddb.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_experiment.py
Labels: v0.1.8

#301 Add citation section
  README.rst
Labels: v0.1.8

#306 Fix EphemeralDB index update after document deletion
  src/orion/core/io/database/ephemeraldb.py
  tests/unittests/core/test_ephemeraldb.py
  tests/unittests/core/test_pickleddb.py
Labels: bug, v0.1.8

#305 Expose trial.params as a dict
  src/orion/core/cli/info.py
  src/orion/core/evc/adapters.py
  src/orion/core/io/orion_cmdline_parser.py
  src/orion/core/utils/format_trials.py
  src/orion/core/worker/trial.py
  src/orion/storage/track.py
  tests/functional/algos/test_algos.py
  tests/functional/branching/test_branching.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/cli/test_info.py
  tests/unittests/core/evc/test_adapters.py
  tests/unittests/core/evc/test_experiment_tree.py
  tests/unittests/core/test_trial.py
  tests/unittests/core/test_utils_format.py
  tests/unittests/core/worker/test_experiment.py
Labels: v0.1.8

#300 Adding Python API
  docs/src/code/client.rst
  docs/src/code/client/experiment.rst
  docs/src/index.rst
  docs/src/install/database.rst
  docs/src/user/algorithms.rst
  docs/src/user/api.rst
  docs/src/user/library/evc_results.rst
  docs/src/user/library/results.rst
  src/orion/client/__init__.py
  src/orion/client/experiment.py
  src/orion/client/manual.py
  src/orion/core/__init__.py
  src/orion/core/cli/info.py
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/resolve_config.py
  src/orion/core/utils/__init__.py
  src/orion/core/utils/format_trials.py
  src/orion/core/utils/tests.py
  src/orion/core/worker/experiment.py
  src/orion/storage/base.py
  src/orion/storage/legacy.py
  tests/conftest.py
  tests/functional/backward_compatibility/test_versions.py
  tests/functional/commands/conftest.py
  tests/functional/commands/test_info_command.py
  tests/functional/commands/test_list_command.py
  tests/functional/commands/test_status_command.py
  tests/functional/demo/test_demo.py
  tests/unittests/client/test_client.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/io/test_orion_cmdline_parser.py
  tests/unittests/core/io/test_resolve_config.py
  tests/unittests/core/test_insert.py
  tests/unittests/core/test_producer.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/storage/test_legacy.py
  tests/unittests/storage/test_storage.py
Labels: v0.1.8

#307 Handle broken trials with python API
  src/orion/client/experiment.py
  tests/unittests/client/test_experiment_client.py
Labels: v0.1.8

#309 Fix doc for bayesopt's alpha
  docs/src/user/algorithms.rst
Labels: v0.1.8

#308 Dev/ignore cli options
  src/orion/core/__init__.py
  src/orion/core/cli/evc.py
  src/orion/core/evc/conflicts.py
  src/orion/core/io/experiment_builder.py
  tests/functional/branching/test_branching.py
  tests/unittests/core/test_branch_config.py
Labels: v0.1.8
