Repository Epistimio/orion, pull requests merged in 2019-07, with the labels that each got.

#192 Add the `setup` command
  docs/src/install/database.rst
  src/orion/core/cli/setup.py
  tests/functional/commands/test_setup_command.py
  tests/unittests/core/cli/test_checks.py
  tests/unittests/core/io/convert_test.py
  tests/unittests/core/io/test_cmdline_parser.py
Labels: v0.1.3

#193 Clean up Documentation for release v0.1.3
  docs/src/code/core/cli.rst
  docs/src/code/core/cli/setup.rst
  docs/src/code/core/cli/test_db.rst
  docs/src/code/core/io/database.rst
  docs/src/code/core/io/database/ephemeraldb.rst
  docs/src/code/core/io/database/pickleddb.rst
  docs/src/examples/cluster.rst
  docs/src/install/database.rst
  docs/src/user/pytorch.rst
  src/orion/core/cli/checks/creation.py
  src/orion/core/cli/checks/presence.py
  src/orion/core/cli/test_db.py
Labels: v0.1.3

#187 [WIP] Implementation of ASHA in orion.algo
  docs/src/code/algo.rst
  docs/src/code/algo/asha.rst
  docs/src/install/plugins.rst
  docs/src/user/algorithms.rst
  setup.py
  src/orion/algo/asha.py
  src/orion/algo/random.py
  src/orion/algo/space.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/producer.py
  src/orion/core/worker/strategy.py
  src/orion/core/worker/trials_history.py
  tests/functional/demo/test_demo.py
  tests/unittests/algo/test_asha.py
  tests/unittests/algo/test_space.py
  tests/unittests/core/experiment.yaml
  tests/unittests/core/mongodb_test.py
  tests/unittests/core/test_ephemeraldb.py
  tests/unittests/core/test_experiment.py
  tests/unittests/core/test_pickleddb.py
  tests/unittests/core/test_producer.py
  tests/unittests/core/test_strategy.py
  tests/unittests/core/test_trial.py
  tox.ini
Labels: v0.1.3

#196 Add CI support for OSX
  .travis.yml
  tests/functional/demo/test_demo.py
  tests/functional/demo/working_dir_config.yaml
Labels: v0.1.4

#198 Add pydocstyle version to tox-flake8 deps
  tox.ini
Labels: v0.1.4

#195 Add a roadmap to the documentation
  MANIFEST.in
  README.rst
  ROADMAP.md
  setup.py
Labels: v0.1.4

#197 Feature/interrupted trials
  src/orion/core/worker/consumer.py
  tests/functional/demo/database_config.yaml
  tests/unittests/core/worker/test_consumer.py
Labels: v0.1.5

#201 added log level for filelock
  src/orion/core/io/database/__init__.py
  tests/unittests/core/test_pickleddb.py
Labels: v0.1.5

#203 Indiana Jones and the Raiders of the Lost Trial
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/worker/experiment.py
  tests/unittests/core/test_experiment.py
Labels: v0.1.5

#207 Fix bug where empty dict would not be alike
  src/orion/core/evc/conflicts.py
  tests/unittests/core/evc/test_conflicts.py
Labels: v0.1.5

#204 Break when broken
  src/orion/core/worker/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  tests/functional/demo/broken_box.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/test_experiment.py
Labels: v0.1.5

#208 Add new cli command to pretty-print a tree of the experiments
  docs/src/conf.py
  src/orion/core/cli/list.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/utils/pptree.py
  tests/functional/commands/test_list_command.py
Labels: v0.1.5

#216 Handle `orion list --name` properly
  src/orion/core/cli/list.py
  tests/functional/commands/test_list_command.py
Labels: bug, v0.1.5

#218 Skip exp update in ExpView
  src/orion/core/worker/experiment.py
  tests/unittests/core/test_experiment.py
Labels: bug, v0.1.5

#220 Remove upsert from `write`
  src/orion/core/io/database/__init__.py
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/io/database/mongodb.py
  src/orion/core/io/database/pickleddb.py
  src/orion/core/worker/experiment.py
  tests/unittests/core/mongodb_test.py
  tests/unittests/core/test_ephemeraldb.py
  tests/unittests/core/test_experiment.py
  tests/unittests/core/test_pickleddb.py
Labels: bug, v0.1.5

#219 Use yaml.safe_load instead of yaml
  src/orion/core/io/convert.py
Labels: v0.1.5

#215 Fix ScriptConfigConflict
  src/orion/core/evc/conflicts.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/sample_config_diff.yml
Labels: bug, v0.1.5

#212 Add a functional test for user script config
  tests/functional/demo/black_box_w_config.py
  tests/functional/demo/script_config.yaml
  tests/functional/demo/test_demo.py
Labels: v0.1.5

#214 Add $ne and handle non-supported operation in EphemeralDB
  src/orion/core/io/database/ephemeraldb.py
  tests/unittests/core/test_ephemeraldb.py
Labels: bug, v0.1.5

#221 Legacy proto
  setup.py
  src/orion/core/worker/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  src/orion/storage/base.py
  src/orion/storage/legacy.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/test_experiment.py
Labels: v0.1.5

#222 Add new `status` command
  conda/meta.yaml
  setup.py
  src/orion/core/cli/status.py
  tests/functional/commands/conftest.py
  tests/functional/commands/test_list_command.py
  tests/functional/commands/test_status_command.py
Labels: v0.1.5

#211 Add info command
  src/orion/core/cli/info.py
  tests/unittests/core/cli/test_info.py
Labels: v0.1.5

#217 Fix race conditions during algo updates
  src/orion/core/worker/experiment.py
  src/orion/core/worker/producer.py
  src/orion/core/worker/trials_history.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/test_experiment.py
  tests/unittests/core/test_producer.py
  tests/unittests/core/worker/test_trials_history.py
Labels: bug, v0.1.5

#223 Don't configure experiment views
  src/orion/core/cli/insert.py
  src/orion/core/cli/status.py
  src/orion/core/worker/experiment.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/test_experiment.py
Labels: bug, v0.1.5

#226 Add new section Monitoring
  docs/src/conf.py
  docs/src/index.rst
  docs/src/user/cli/info.rst
  docs/src/user/evc.rst
  docs/src/user/library/evc_results.rst
  docs/src/user/library/results.rst
  docs/src/user/monitoring.rst
  docs/src/user/pytorch.rst
Labels: v0.1.5

#230 Update Roadmap for release v0.1.5
  ROADMAP.md
Labels: v0.1.5

#234 Handle broken refers in experiment configuration
  src/orion/core/cli/info.py
  src/orion/core/cli/list.py
  src/orion/core/worker/experiment.py
  tests/functional/commands/conftest.py
  tests/functional/commands/test_info_command.py
  tests/functional/commands/test_list_command.py
Labels: bug, v0.1.5

#235 Move TrialMonitor/TrialPacemaker inside consumer
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/trial_pacemaker.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/core/worker/test_trial_pacemaker.py
Labels: bug, v0.1.5

#236 Bring back space.{un}pack_point but deprecate them
  src/orion/algo/space.py
Labels: bug, v0.1.5

#240 Add `version` to Experiment
  src/orion/core/worker/experiment.py
  src/orion/storage/legacy.py
  tests/conftest.py
  tests/requirements.txt
  tests/unittests/core/test_experiment.py
Labels: v0.1.6

#237 Fix Trial ID mismatch with higher dimension shapes
  tests/unittests/core/test_trial.py
Labels: v0.1.6

#239 Add configuration object for global configuration
  src/orion/core/io/config.py
  src/orion/core/io/database/ephemeraldb.py
  src/orion/core/utils/flatten.py
  tests/unittests/core/io/test_config.py
Labels: v0.1.6

#241 remove remaining Database() calls
  setup.py
  src/orion/core/cli/list.py
  src/orion/core/cli/status.py
  src/orion/core/evc/conflicts.py
  src/orion/core/evc/experiment.py
  src/orion/core/io/database/mongodb.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/interactive_commands/branching_prompt.py
  src/orion/core/utils/__init__.py
  src/orion/core/worker/experiment.py
  src/orion/storage/base.py
  src/orion/storage/legacy.py
  tests/conftest.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/io/database_test.py
  tests/unittests/core/test_experiment.py
  tests/unittests/core/worker/test_trial_pacemaker.py
Labels: v0.1.6
