Repository Epistimio/orion, pull requests merged in 2020-06, with the labels that each got.

#398 Update TOX configuration
  .flake8
  .pylintrc
  MANIFEST.in
  dev-requirements.txt
  docs/src/developer/release.rst
  tox.ini
Labels: enhancement

#397 Add doc about label categories
  docs/src/developer/standards.rst
Labels: documentation, v0.1.8

#401 Catch keyboard interrupt in Python API
  src/orion/client/experiment.py
  tests/unittests/client/test_experiment_client.py
Labels: v0.1.8

#402 Round ASHA budget properly
  src/orion/algo/asha.py
  tests/unittests/algo/test_asha.py
Labels: v0.1.8

#409 Document Windows compatibility
  docs/src/install/core.rst
Labels: documentation, v0.1.8

#404 Handle producer config in experiment section
  docs/src/plugins/install.rst
  docs/src/user/algorithms.rst
  docs/src/user/script.rst
  src/orion/core/io/resolve_config.py
Labels: v0.1.8

#405 Update Plugins documentation section
  docs/src/plugins/algorithms.rst
  docs/src/plugins/base.rst
Labels: v0.1.8

#403 Promote Oríon's agnosticity
  README.rst
  docs/src/user/script.rst
Labels: documentation, v0.1.8

#408 Print help when calling `orion` alone
  src/orion/core/cli/__init__.py
  src/orion/core/cli/base.py
  src/orion/core/cli/hunt.py
  src/orion/core/cli/init_only.py
  src/orion/core/cli/insert.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/utils/exceptions.py
  tests/functional/commands/test_db_commands.py
  tests/functional/commands/test_hunt_command.py
  tests/functional/commands/test_info_command.py
  tests/functional/commands/test_init_only_command.py
  tests/functional/commands/test_insert_command.py
  tests/functional/demo/test_demo.py
Labels: v0.1.8

#406 Fix mongodb count for v < 3.7
  src/orion/core/io/database/mongodb.py
Labels: v0.1.8

#410 Raise exception when no prior is provided
  src/orion/core/io/experiment_builder.py
  tests/functional/commands/test_hunt_command.py
  tests/unittests/core/io/test_experiment_builder.py
Labels: v0.1.8
