Repository Epistimio/orion, pull requests merged in 2020-04, with the labels that each got.

#375 Update the documentation structure
  README.rst
  docs/src/index.rst
  docs/src/install/core.rst
  docs/src/install/database.rst
  docs/src/plugins/algorithms.rst
  docs/src/plugins/install.rst
  docs/src/tutorials/cluster.rst
  docs/src/tutorials/pytorch.rst
  docs/src/tutorials/pytorch_a2c_ppo.rst
  docs/src/tutorials/pytorch_cifar.rst
  docs/src/tutorials/scikit-learn.rst
  docs/src/user/algorithms.rst
  docs/src/user/api.rst
  docs/src/user/script.rst
  examples/scikitlearn-iris/README.md
Labels: documentation, v0.1.8

#377 Ignore test files for code coverage
  codecov.yml
Labels: v0.1.8

#374 Fix --debug
  LICENSE
  docs/src/code/storage.rst
  docs/src/code/storage/base.rst
  docs/src/code/storage/legacy.rst
  docs/src/code/storage/track.rst
  docs/src/index.rst
  docs/src/user/api.rst
  docs/src/user/storage.rst
  src/orion/client/__init__.py
  src/orion/core/__init__.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/resolve_config.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/strategy.py
  src/orion/storage/base.py
  src/orion/storage/legacy.py
  src/orion/storage/track.py
  tests/conftest.py
  tests/functional/demo/test_demo.py
  tests/functional/example/conftest.py
  tests/functional/example/test_scikit_learn.py
  tests/unittests/client/test_client.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/test_strategy.py
  tests/unittests/storage/test_legacy.py
  tests/unittests/storage/test_storage.py
Labels: bug, v0.1.8

#373 Making upper bound inclusive
  src/orion/algo/space.py
  tests/functional/commands/test_status_command.py
  tests/unittests/algo/test_base.py
  tests/unittests/algo/test_space.py
  tests/unittests/core/test_transformer.py
Labels: bug, v0.1.8

#379 Cite latest version of Oríon by default
  README.rst
Labels: documentation

#364 Add stress test
  MANIFEST.in
  docs/src/developer/stress.rst
  docs/src/developer/test.png
  docs/src/developer/testing.rst
  tests/stress/client/stress_experiment.py
  tests/stress/requirements.txt
  tox.ini
Labels: v0.1.8

#380 Refreshed introduction of Oríon's features
  README.rst
Labels: documentation

#383 update asha and hyperband
  src/orion/algo/asha.py
  src/orion/algo/hyperband.py
  src/orion/algo/space.py
  tests/unittests/algo/test_asha.py
  tests/unittests/algo/test_hyperband.py
  tests/unittests/algo/test_space.py
Labels: v0.1.8
