Repository Epistimio/orion, pull requests merged in 2020-08, with the labels that each got.

#423 REST Service API
  conda/conda_build.sh
  conda/meta.yaml
  docs/src/user/monitoring.rst
  docs/src/user/rest_api.rst
  setup.py
  src/orion/core/cli/serve.py
  src/orion/core/worker/trial.py
  src/orion/serving/__init__.py
  src/orion/serving/experiments_resource.py
  src/orion/serving/runtime.py
  src/orion/serving/webapi.py
  tests/functional/serving/conftest.py
  tests/functional/serving/test_experiments_endpoint.py
  tests/functional/serving/test_root.py
  tests/unittests/core/worker/test_trial.py
Labels: feature

#437 Adding trials/ REST resource
  src/orion/core/worker/trial.py
  src/orion/serving/experiments_resource.py
  src/orion/serving/parameters.py
  src/orion/serving/responses.py
  src/orion/serving/trials_resource.py
  src/orion/serving/webapi.py
  tests/functional/serving/test_experiments_endpoint.py
  tests/functional/serving/test_trials_resource.py
  tests/unittests/core/worker/test_trial.py
Labels: feature

#438 REST plotting endpoint with regret plots
  src/orion/serving/plots_resources.py
  src/orion/serving/webapi.py
  tests/functional/serving/test_plots_resource.py
Labels: feature

#440 CLI documentation improvements
  docs/src/code/core/cli.rst
  src/orion/core/cli/base.py
  src/orion/core/cli/db/rm.py
  src/orion/core/cli/db/set.py
  src/orion/core/cli/db/setup.py
  src/orion/core/cli/db/test.py
  src/orion/core/cli/db/upgrade.py
  src/orion/core/cli/db_main.py
  src/orion/core/cli/hunt.py
  src/orion/core/cli/info.py
  src/orion/core/cli/init_only.py
  src/orion/core/cli/insert.py
  src/orion/core/cli/list.py
  src/orion/core/cli/serve.py
  src/orion/core/cli/setup.py
  src/orion/core/cli/status.py
  src/orion/core/cli/test_db.py
Labels: documentation, enhancement

#435 Add `completed` field to `info` cmd
  src/orion/core/utils/format_terminal.py
  tests/unittests/core/cli/test_info.py
Labels: enhancement

#442 Remove outdated `branch_from` parameter documentation in `experiment_builder.build()`
  src/orion/core/io/experiment_builder.py
Labels: documentation

#443 Sort modules and extensions alphabetically
  conda/meta.yaml
  docs/src/conf.py
  setup.py
Labels: enhancement

#439 Add orion.client.get_experiment()
  src/orion/client/__init__.py
  tests/conftest.py
  tests/unittests/client/test_client.py
Labels: feature

#445 Print user friendly err msg if script inexecutable
  src/orion/core/cli/base.py
  src/orion/core/utils/exceptions.py
  src/orion/core/worker/consumer.py
  tests/functional/demo/test_demo.py
Labels: documentation

#441 Documenting the full specification of the web api
  docs/requirements.txt
  docs/src/conf.py
  docs/src/user/monitoring.rst
  docs/src/user/rest_api.rst
  docs/src/user/web_api.rst
  src/orion/core/worker/trial.py
Labels: documentation
