Repository Epistimio/orion, pull requests merged in 2020-02, with the labels that each got.

#327 Formatted commands and added a command description
  docs/src/examples/pytorch_cifar.rst
Labels: documentation, v0.1.8

#329 Clone via HTTPS instead of SSH
  docs/src/examples/pytorch_cifar.rst
  docs/src/user/pytorch.rst
Labels: enhancement, v0.1.8

#331 PR: add precision to Real
  docs/src/user/searchspace.rst
  src/orion/algo/space.py
  src/orion/core/worker/transformer.py
  tests/functional/algos/test_algos.py
  tests/functional/branching/test_branching.py
  tests/functional/demo/script_config.yaml
  tests/functional/demo/test_demo.py
  tests/unittests/algo/test_space.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/sample_config.json
  tests/unittests/core/sample_config.yml
  tests/unittests/core/sample_config_diff.yml
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/test_transformer.py
Labels: v0.1.8

#332 Updated the roadmap for v0.1.8
  ROADMAP.md
Labels: documentation, v0.1.8

#340 Added v0.1.9 to the roadmap
  ROADMAP.md
Labels: documentation

#343 Add more helper functions for cmdline client
  docs/src/code/client.rst
  docs/src/code/client/cli.rst
  docs/src/examples/pytorch_a2c_ppo.rst
  docs/src/examples/pytorch_cifar.rst
  docs/src/reference/.gitkeep
  docs/src/user/api.rst
  docs/src/user/pytorch.rst
  src/orion/algo/base.py
  src/orion/client/__init__.py
  src/orion/client/cli.py
  src/orion/core/__init__.py
  src/orion/core/cli/base.py
  src/orion/core/utils/exceptions.py
  src/orion/core/worker/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/storage/legacy.py
  tests/functional/client/black_box.py
  tests/functional/client/orion_config.yaml
  tests/functional/client/test_cli_client.py
  tests/unittests/client/test_client.py
  tests/unittests/storage/test_legacy.py
Labels: v0.1.8

#303 Drop python3.5 support and add python3.8
  .travis.yml
  conda/conda_build.sh
  setup.py
  tests/functional/gradient_descent_algo/setup.py
  tox.ini
Labels: v0.1.8

#345 Print important information at end of worker
  docs/src/code/core/utils.rst
  docs/src/code/core/utils/format_terminal.rst
  src/orion/core/cli/info.py
  src/orion/core/utils/format_terminal.py
  src/orion/core/worker/__init__.py
  tests/unittests/core/cli/test_info.py
Labels: v0.1.8

#341 Add support for non-standard -args
  src/orion/core/io/cmdline_parser.py
  tests/unittests/core/io/test_cmdline_parser.py
  tests/unittests/core/io/test_orion_cmdline_parser.py
Labels: v0.1.8

#342 Inconsistent output in orion status and orion list
  .gitignore
  src/orion/core/cli/list.py
  src/orion/core/cli/status.py
  tests/functional/commands/test_list_command.py
  tests/functional/commands/test_status_command.py
Labels: v0.1.8

#346 Add comprehensive error message for branching err
  src/orion/client/__init__.py
  src/orion/core/cli/base.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/utils/exceptions.py
  tests/functional/branching/test_branching.py
  tests/unittests/client/test_client.py
  tests/unittests/core/io/test_experiment_builder.py
Labels: documentation, v0.1.8
