Repository Epistimio/orion, pull requests merged in 2020-03, with the labels that each got.

#344 Removed empty sections and TODOs
  docs/src/developer/standards.rst
  docs/src/index.rst
  docs/src/plugins/algorithms.rst
  docs/src/plugins/analysis.rst
  docs/src/plugins/base.rst
  docs/src/plugins/database.rst
Labels: documentation, v0.1.8

#350 Enabling localized testing via tox
  tox.ini
Labels: testing, v0.1.8

#338 Changed documentation to support non-executable python files
  docs/src/examples/cluster.rst
  docs/src/examples/pytorch_a2c_ppo.rst
  docs/src/examples/pytorch_cifar.rst
  docs/src/user/cli/info.rst
  docs/src/user/evc.rst
  docs/src/user/pytorch.rst
Labels: documentation, v0.1.8

#351 Update fidelity sample method to honor required n_samples
  src/orion/algo/space.py
  tests/unittests/algo/test_space.py
Labels: v0.1.8

#349 Make global, local and cmdline args coherent
  docs/src/index.rst
  docs/src/user/config.rst
  src/orion/client/__init__.py
  src/orion/client/experiment.py
  src/orion/core/__init__.py
  src/orion/core/cli/base.py
  src/orion/core/cli/evc.py
  src/orion/core/cli/hunt.py
  src/orion/core/evc/conflicts.py
  src/orion/core/io/config.py
  src/orion/core/io/experiment_branch_builder.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/resolve_config.py
  src/orion/core/worker/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  tests/conftest.py
  tests/functional/demo/test_demo.py
  tests/unittests/core/io/orion_config.yaml
  tests/unittests/core/io/test_config.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/io/test_resolve_config.py
  tox.ini
Labels: v0.1.8

#354 Hyperband oob
  setup.py
  src/orion/algo/hyperband.py
  tests/functional/algos/hyperband.yaml
  tests/functional/algos/test_algos.py
  tests/unittests/algo/test_hyperband.py
Labels: v0.1.8

#352 Generic cardinality check in base algorithm
  src/orion/algo/base.py
  src/orion/algo/random.py
  src/orion/core/worker/primary_algo.py
  tests/conftest.py
  tests/unittests/algo/test_base.py
Labels: v0.1.8

#356 Contribution guidelines
  CONTRIBUTING.md
  MANIFEST.in
  README.rst
  docs/src/developer/overview.rst
  docs/src/index.rst
Labels: documentation, v0.1.8

#339 Minimalist example with scikit-learn
  .gitignore
  MANIFEST.in
  docs/src/examples/scikit-learn.rst
  docs/src/index.rst
  examples/README.md
  examples/scikitlearn-iris/README.md
  examples/scikitlearn-iris/main.py
  examples/scikitlearn-iris/requirements.txt
  setup.py
  tests/functional/example/conftest.py
  tests/functional/example/orion_config.yaml
  tests/functional/example/test_scikit_learn.py
  tox.ini
Labels: documentation, v0.1.8

#361 Avoid duplicates in RandomSearch
  src/orion/algo/base.py
  src/orion/algo/random.py
  tests/unittests/algo/test_random.py
Labels: v0.1.8

#360 Add max_trials to algorithm.is_done
  src/orion/algo/base.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/producer.py
  tests/conftest.py
  tests/unittests/algo/test_base.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/core/worker/test_producer.py
Labels: bug, v0.1.8

#362 Handle timeout in DBs (PickledDB in particular)
  src/orion/core/io/database/__init__.py
  src/orion/core/io/database/mongodb.py
  src/orion/core/io/database/pickleddb.py
  tests/unittests/core/test_pickleddb.py
Labels: v0.1.8

#366 Fix broken-link in monitoring
  docs/src/user/library/evc_results.rst
Labels: documentation, v0.1.8

#365 Update developer documentation
  CONTRIBUTING.md
  docs/src/developer/ci.rst
  docs/src/developer/documenting.rst
  docs/src/developer/installing.rst
  docs/src/developer/overview.rst
  docs/src/developer/standards.rst
  docs/src/developer/testing.rst
  docs/src/index.rst
  docs/src/install/core.rst
  docs/src/install/database.rst
Labels: documentation, v0.1.8

#370 Add link to cookiecutter template
  docs/src/plugins/base.rst
Labels: documentation, v0.1.8
