Repository Epistimio/orion, pull requests merged in 2020-07, with the labels that each got.

#419 Merging master back to develop after release.
  README.rst
  docs/src/developer/release.rst
  examples/scikitlearn-iris/README.md
  src/orion/core/io/database/pickleddb.py
  src/orion/core/worker/strategy.py
Labels: v0.1.8

#416 Merging Sequential and Service API
  docs/src/user/api.rst
Labels: documentation

#353 Code of conduct
  CODE_OF_CONDUCT.md
  MANIFEST.in
Labels: documentation

#413 Refresh database documentation
  docs/src/code/core/io/database/ephemeraldb.rst
  docs/src/developer/testing.rst
  docs/src/install/database.rst
Labels: documentation

#400 Plotting API Starter
  .gitignore
  MANIFEST.in
  conda/meta.yaml
  docs/src/code/plotting.rst
  docs/src/index.rst
  examples/plotting/database.pkl
  examples/plotting/local.yaml
  examples/plotting/plotting-api.ipynb
  setup.py
  src/orion/client/experiment.py
  src/orion/core/utils/tests.py
  src/orion/plotting/backend_plotly.py
  src/orion/plotting/base.py
  tests/functional/algos/test_algos.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/plotting/test_plot_accessor.py
  tests/unittests/plotting/test_plotly_backend.py
  tests/unittests/storage/test_legacy.py
Labels: feature

#429 Quit if code changed between two trials execution
  src/orion/core/io/experiment_builder.py
  src/orion/core/worker/consumer.py
  tests/unittests/core/worker/test_consumer.py
Labels: bug

#431 Move testing support code to `orion.testing`
  conda/meta.yaml
  setup.py
  src/orion/client/__init__.py
  src/orion/core/io/database/__init__.py
  src/orion/core/utils/__init__.py
  src/orion/core/utils/singleton.py
  src/orion/storage/base.py
  src/orion/testing/__init__.py
  src/orion/testing/state.py
  tests/conftest.py
  tests/functional/demo/test_demo.py
  tests/stress/client/stress_experiment.py
  tests/unittests/client/test_client.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/conftest.py
  tests/unittests/core/io/database_test.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/plotting/test_plot_accessor.py
  tests/unittests/plotting/test_plotly_backend.py
  tests/unittests/storage/test_legacy.py
  tests/unittests/storage/test_storage.py
Labels: enhancement, testing
