Repository Epistimio/orion, pull requests merged in 2021-09, with the labels that each got.

#634 Support to configure executor for benchmark
  src/orion/benchmark/__init__.py
  src/orion/benchmark/benchmark_client.py
  src/orion/client/__init__.py
  src/orion/client/experiment.py
  tests/unittests/benchmark/test_benchmark_client.py
  tests/unittests/client/test_experiment_client.py
Labels: enhancement

#650 Fix TPE sampling in narrow spaces
  src/orion/algo/tpe.py
  tests/unittests/algo/test_tpe.py
Labels: bug

#651 Add missing documentation for EVC enable option
  docs/src/install/gettingstarted.rst
  docs/src/user/config.rst
  docs/src/user/evc.rst
Labels: documentation

#655 Use user_script_config from parser in EVC
  src/orion/core/evc/conflicts.py
  tests/functional/branching/test_branching.py
Labels: bug

#652 Clear error message for dup branching error
  src/orion/core/io/experiment_builder.py
Labels: documentation

#654 Fix shape argument in categorical dims
  src/orion/algo/space.py
  src/orion/core/evc/adapters.py
  tests/unittests/algo/test_space.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_adapters.py
  tests/unittests/core/evc/test_resolutions.py
Labels: bug

#658 Support linearize log integer properly
  src/orion/algo/tpe.py
  src/orion/core/worker/transformer.py
  tests/unittests/algo/test_tpe.py
  tests/unittests/core/test_transformer.py
Labels: bug

#659 Revert to default inf max_trials and pool-size of 1
  docs/src/tutorials/pytorch-mnist.rst
  docs/src/user/config.rst
  src/orion/client/experiment.py
  src/orion/core/__init__.py
  src/orion/core/cli/hunt.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/utils/format_terminal.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/producer.py
  src/orion/serving/responses.py
  src/orion/testing/evc.py
  tests/functional/algos/test_algos.py
  tests/functional/configuration/test_all_options.py
  tests/functional/demo/test_demo.py
  tests/functional/serving/test_experiments_resource.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/cli/test_info.py
  tests/unittests/core/evc/test_experiment_tree.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/io/test_resolve_config.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/core/worker/test_producer.py
Labels: enhancement

#663 Release candidate v0.1.17rc1
  README.rst
  ROADMAP.md
  docs/src/install/gettingstarted.rst
  docs/src/tutorials/pytorch-mnist.rst
  docs/src/user/config.rst
  docs/src/user/evc.rst
  src/orion/algo/space.py
  src/orion/algo/tpe.py
  src/orion/benchmark/__init__.py
  src/orion/benchmark/benchmark_client.py
  src/orion/client/__init__.py
  src/orion/client/experiment.py
  src/orion/core/__init__.py
  src/orion/core/cli/hunt.py
  src/orion/core/cli/list.py
  src/orion/core/evc/adapters.py
  src/orion/core/evc/conflicts.py
  src/orion/core/io/experiment_builder.py
  src/orion/core/io/resolve_config.py
  src/orion/core/utils/format_terminal.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/producer.py
  src/orion/core/worker/transformer.py
  src/orion/plotting/backend_plotly.py
  src/orion/serving/responses.py
  src/orion/testing/evc.py
  tests/functional/algos/test_algos.py
  tests/functional/backward_compatibility/test_versions.py
  tests/functional/backward_compatibility/versions.txt
  tests/functional/branching/test_branching.py
  tests/functional/commands/test_list_command.py
  tests/functional/configuration/test_all_options.py
  tests/functional/demo/test_demo.py
  tests/functional/serving/test_experiments_resource.py
  tests/requirements.txt
  tests/unittests/algo/test_space.py
  tests/unittests/algo/test_tpe.py
  tests/unittests/benchmark/test_benchmark_client.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/cli/test_info.py
  tests/unittests/core/conftest.py
  tests/unittests/core/evc/test_adapters.py
  tests/unittests/core/evc/test_conflicts.py
  tests/unittests/core/evc/test_experiment_tree.py
  tests/unittests/core/evc/test_resolutions.py
  tests/unittests/core/io/test_experiment_builder.py
  tests/unittests/core/io/test_resolve_config.py
  tests/unittests/core/test_branch_config.py
  tests/unittests/core/test_transformer.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/core/worker/test_producer.py
Labels: release
