Repository Epistimio/orion, pull requests merged in 2021-05, with the labels that each got.

#601 Orion python api in parallel
  setup.py
  src/orion/benchmark/__init__.py
  src/orion/benchmark/benchmark_client.py
  src/orion/client/__init__.py
  src/orion/client/experiment.py
  src/orion/core/io/database/mongodb.py
  src/orion/core/worker/experiment.py
  src/orion/storage/track.py
  tests/functional/algos/test_algos.py
  tests/unittests/benchmark/test_benchmark_client.py
  tests/unittests/client/test_client.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/database/test_database.py
  tests/unittests/core/worker/test_experiment.py
  tests/unittests/storage/test_storage.py
Labels: feature

#605 Refactor `hunt` command to reuse `ExperimentClient.workon`
  .pylintrc
  docs/src/conf.py
  src/orion/client/experiment.py
  src/orion/core/cli/hunt.py
  src/orion/core/utils/exceptions.py
  src/orion/core/worker/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/core/worker/experiment.py
  src/orion/core/worker/producer.py
  src/orion/core/worker/trial.py
  src/orion/storage/legacy.py
  tests/functional/client/test_cli_client.py
  tests/functional/configuration/test_all_options.py
  tests/functional/demo/orion_config.yaml
  tests/functional/demo/orion_config_other.yaml
  tests/functional/demo/orion_config_random.yaml
  tests/functional/demo/test_demo.py
  tests/functional/gradient_descent_algo/src/orion/algo/gradient_descent.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/worker/test_consumer.py
  tests/unittests/storage/test_legacy.py
  tox.ini
Labels: enhancement

#604 Add has_suggested/observed, new test-suite and re-implementation of ASHA
  conda/meta.yaml
  docs/src/code/testing.rst
  docs/src/code/testing/algo.rst
  docs/src/code/testing/plotting.rst
  docs/src/code/testing/space.rst
  docs/src/code/testing/state.rst
  docs/src/index.rst
  docs/src/user/algorithms.rst
  setup.py
  src/orion/algo/asha.py
  src/orion/algo/base.py
  src/orion/algo/evolution_es.py
  src/orion/algo/gridsearch.py
  src/orion/algo/hyperband.py
  src/orion/algo/mutate_functions.py
  src/orion/algo/random.py
  src/orion/algo/tpe.py
  src/orion/benchmark/task/branin.py
  src/orion/core/__init__.py
  src/orion/core/worker/primary_algo.py
  src/orion/core/worker/producer.py
  src/orion/testing/algo.py
  src/orion/testing/plotting.py
  src/orion/testing/space.py
  src/orion/testing/state.py
  tests/conftest.py
  tests/functional/algos/test_algos.py
  tests/functional/backward_compatibility/python_api.py
  tests/functional/client/test_cli_client.py
  tests/functional/demo/test_demo.py
  tests/functional/gradient_descent_algo/src/orion/algo/gradient_descent.py
  tests/requirements.txt
  tests/unittests/algo/test_asha.py
  tests/unittests/algo/test_base.py
  tests/unittests/algo/test_evolution_es.py
  tests/unittests/algo/test_gridsearch.py
  tests/unittests/algo/test_hyperband.py
  tests/unittests/algo/test_random.py
  tests/unittests/algo/test_tpe.py
  tests/unittests/benchmark/test_tasks.py
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/test_primary_algo.py
  tests/unittests/core/worker/test_producer.py
  tox.ini
Labels: bug, documentation, enhancement

#608 Add Executor class and CLI arguments for parallelism
  docs/src/code/executor.rst
  docs/src/code/executor/base.rst
  docs/src/code/executor/dask.rst
  docs/src/code/executor/joblib.rst
  docs/src/index.rst
  docs/src/user/config.rst
  examples/dask_example.py
  setup.py
  src/orion/algo/base.py
  src/orion/client/__init__.py
  src/orion/client/experiment.py
  src/orion/core/__init__.py
  src/orion/core/cli/db/setup.py
  src/orion/core/cli/hunt.py
  src/orion/core/io/convert.py
  src/orion/core/io/database/mongodb.py
  src/orion/core/utils/__init__.py
  src/orion/core/worker/consumer.py
  src/orion/executor/base.py
  src/orion/executor/dask_backend.py
  src/orion/executor/joblib_backend.py
  tests/conftest.py
  tests/functional/commands/test_setup_command.py
  tests/functional/configuration/conftest.py
  tests/functional/configuration/test_all_options.py
  tests/functional/demo/test_demo.py
  tests/requirements.txt
  tests/unittests/client/test_experiment_client.py
  tests/unittests/core/io/test_resolve_config.py
  tests/unittests/core/test_utils.py
Labels: feature

#609 Test different type of categorical dims
  src/orion/algo/tpe.py
  src/orion/testing/algo.py
  tests/unittests/algo/test_tpe.py
Labels: bug
