Repository Epistimio/orion, pull requests merged in 2022-03, with the labels that each got.

#828 Handle all tests using Dask
  tests/functional/storage/test_io.py
  tests/unittests/benchmark/task/profet/conftest.py
  tests/unittests/executor/test_executor.py
Labels: bug, low

#813 Test algo can handle broken trials
  src/orion/algo/base.py
  src/orion/testing/algo.py
Labels: ci

#867 Detect _param_names from __init__ signature
  src/orion/algo/base.py
  tests/unittests/algo/test_base.py
Labels: enhancement

#874 Simplify setting test phases in Test Classes
  src/orion/testing/algo.py
  tests/unittests/algo/pbt/test_pbt.py
  tests/unittests/algo/test_asha.py
  tests/unittests/algo/test_evolution_es.py
  tests/unittests/algo/test_gridsearch.py
  tests/unittests/algo/test_hyperband.py
  tests/unittests/algo/test_random.py
  tests/unittests/algo/test_tpe.py
Labels: ci
